### ISSUE TITLE
Sección de apoyo al Plan de Estudios

### ISSUE THREAD

**Issue by Vivallo04** [aseic/aseic.github.io#10]
Hola, la idea de esta sección es que contenga material de apoyo de CADA UNO DE LOS CURSOS que actualmente están en el plan de estudios. Y esto incluye, **lecturas recomendadas, programa del curso, exámenes anteriores, prácticas, quices, proyectos y otro tipo de material adicional**. 

La idea es enfrentar una problemática que pienso que hay pero que actualmente no hay nada que proponga una solución, así como que los estudiantes no saben de qué se trata un curso, profesores que no son claros con el material complementario que se puede llevar, no hay prácticas adicionales, y esto además ayudará a la planificación de matrícula de cada estudiante.

**Comment by Vivallo04** [comment]
Yo puedo colaborar con el desarrollo inicial de este _feature_, pero no poseo claramente todo el material necesario para hacerlo solo. Y además, recomendaría poner un _deadline_, recomendaría en este break que tenemos de final de semestre, para realizarlo y avanzar lo que más podamos, porque o sino es algo que se "va a dejar botado". 

Pienso que esto va a ser clave para la importacia de esta plataforma y la motivación de cada estudiante en su desempeño académico. Propondría crear un Trello board aunque sea para la planificación de cosas como estas, porque hacer esto requiere filtrar la información que eventualmente le estaremos pidiendo a la comunidad, y ser claros en el progreso que llevamos.

**Comment by alejandrodp** [comment]
Hola, me parece muy buena la idea. Sí, tiene toda la razón con lo de aprovechar este lapso para mejorar la página y que sea más útil, ese es el objetivo junto con las actividades del otro semestre. 

Con los projects de github también se pueden organizar las features y me parece mejor para centralizar el roadmap y discusiones en un solo lugar.

Respecto a la información voy a pedirle a la coordinación los programas y apenas los tenga podemos reunirnos para pensar un poco más esto si quiere, ahí en el discord de la junta y así que si alguien más quiere entrar también a aportar ideas o escuchar que pueda hacerlo.

**Comment by Vivallo04** [comment]
Me parece muy bien la idea de utilizar GitHub Projects para esto, no lo había pensado. Y genial, pongamos una fecha para la discusión de este tema, **a las ya**, para no perder el momentum. E igual pienso que hay que presionar a la coordinación lo más que se pueda para que no sea un inconveniente para nosotros y dejarles claro cuál es nuestro objetivo.

**Comment by alejandrodp** [comment]
Quisiera que fuera ya, de verdad no es porque no quiera es porque estoy terminando mi semestre jaja, el miércoles hay examen de sys y mañana presentación de proyecto de taller de digitales. Pero tiene razón, le parece el viernes?

**Comment by Vivallo04** [comment]
Sí, genial, el viernes me queda bien. Suerte en el final de semestre!

**Comment by alejandrodp** [comment]
Se movió a #11
