### ISSUE TITLE
Agregar una sección de guía y reglas para contribución

### ISSUE THREAD

**Issue by Josfemova** [aseic/aseic.github.io#6]
Sería bueno agregar una guía de como hacer una contribución al repositorio y qué lineamientos deben seguirse. Algunos ya sabrán el flujo normal de contribuir en repos de OSS pero lastimosamente eso no se toca mucho en la carrera. Otros ya saben markdown pero no han tocado mdbook

También sería bueno tener establecido un CoC (Code of Conduct) para contribuciones y en general comportamiento en el grupo de repos, de forma que se pueda mantener la interacción lo más constructiva posible. 

Ambas cosas se deberían agregar tanto en el book como a un `README.md` del repo. 

Yo puedo sentarme a escribir la guía de como hacer una primera contribución, pero la parte del CoC creo que tocaría decidir interno a la asocia. Quedo atento a opiniones.

**Comment by alejandrodp** [comment]
Gracias, puede hacer una propuesta y ponerla en un PR para revisarla. Pero sí, es cierto que eso es buena idea para que la gente pueda introducrise rápidamente a contribuir.

**Comment by alejandrodp** [comment]
Se agregó una sección de contribución y se replicó en el README. Ver 0354e7e2330be97c02fe09145928ecfc370bce05 y c3c1816b7a5c81b4b068ef2b43b218c89b3e78ff
