### ISSUE TITLE
Considerar crear una sección de investigación

### ISSUE THREAD

**Issue by Josfemova** [aseic/aseic.github.io#8]
Profesores y estudiantes de CE participan en proyectos de investigación, ya sea dentro del área o en laboratorios de otras unidades académicas de la universidad. Puede ser provechoso entonces tener una sección en la que se liste:

- Unidad Académica
  - Laboratorio
    - Proyecto
      - Estudiantes de CE involucrados en dicho proyecto
      - Profesores que a los que debería contactar alguien interesado en dicho lab/proyecto

Se debería preferir proveer el link del telegram para info de contacto, pero en caso de que dicha información no esté disponible, un correo electrónico u otro medio de contacto provisto por la persona en cuestión.   

Esto siento facilitaría la inclusión de estudiantes de CE en proyectos de investigación. Muchas veces no se sabe a quién contactar, hay mucho dime que te diré y uno como que tiene que estar en el lugar correcto en el momento correcto para encontrar algo interesante. Tener un canal más directo para involucrarse en investigación siento que sería provechoso.

**Comment by alejandrodp** [comment]
Ajá, es buena idea, la sección de grupos estudiantiles lleva una línea similar. Puede proponer una sección en un PR y ver que tal.

**Comment by alejandrodp** [comment]
Se aplicaron las recomendaciones de este issue y relacionados en 4ce6f9615. Por lo que procedo a cerrarlo.
